"""add fixed expense check-ins

A fixed expense no longer counts by itself: from `confirm_from` on, each occurrence waits
for the user to say whether they paid it (one row per answer). Existing expenses get the
day of the migration, so everything before it keeps counting exactly as it did.

Revision ID: 320f0e98915a
Revises: 5f863c982595
Create Date: 2026-10-10 13:45:39.142005

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "320f0e98915a"
down_revision: str | Sequence[str] | None = "5f863c982595"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fixed_expense_check_ins",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("fixed_expense_id", sa.Uuid(), nullable=False),
        sa.Column("occurs_on", sa.Date(), nullable=False),
        sa.Column("paid", sa.Boolean(), nullable=False),
        sa.Column(
            "answered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["fixed_expense_id"],
            ["fixed_expenses.id"],
            name=op.f("fk_fixed_expense_check_ins_fixed_expense_id_fixed_expenses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_fixed_expense_check_ins_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixed_expense_check_ins")),
        sa.UniqueConstraint(
            "fixed_expense_id",
            "occurs_on",
            name=op.f("uq_fixed_expense_check_ins_fixed_expense_id"),
        ),
    )
    op.create_index(
        op.f("ix_fixed_expense_check_ins_user_id"),
        "fixed_expense_check_ins",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "fixed_expenses",
        sa.Column(
            "confirm_from", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fixed_expenses", "confirm_from")
    op.drop_index(op.f("ix_fixed_expense_check_ins_user_id"), table_name="fixed_expense_check_ins")
    op.drop_table("fixed_expense_check_ins")
    # ### end Alembic commands ###
